name: 'MongoDB in GitHub Actions'
description: 'Start a MongoDB server (on default port 27017 or a custom port)'

branding:
  icon: 'database'
  color: 'green'

inputs:
  mongodb-version:
    description: 'MongoDB version to use (default "latest")'
    required: false
    default: 'latest'

  mongodb-replica-set:
    description: 'MongoDB replica set name (default: none)'
    required: false
    default: ''

  mongodb-port:
    description: 'MongoDB port to use (default: 27017)'
    required: false
    default: 27017

  mongodb-db:
    description: 'MongoDB db to create (default: none)'
    required: false
    default: ''

  mongodb-username:
    description: 'MongoDB root username (default: none)'
    required: false
    default: ''

  mongodb-password:
    description: 'MongoDB root password (default: none)'
    required: false
    default: ''

  host-container-hostname:
    description: 'Name of the runner (default: none)'
    required: false
    default: ''

outputs:
  mongodb-container-id:
    description: 'ID for the generated container'
  mongodb-container-name:
    description: 'Name for the generated container'
  mongodb-container-ip-address:
    description: 'IP address for the generated container'
  mongodb-container-port:
    description: 'Port for the generated container'

runs:
  using: 'docker'
  image: 'Dockerfile'
  post-entrypoint: '/cleanup.sh'
  args:
    - ${{ inputs.mongodb-version }}
    - ${{ inputs.mongodb-replica-set }}
    - ${{ inputs.mongodb-port }}
    - ${{ inputs.mongodb-db }}
    - ${{ inputs.mongodb-username }}
    - ${{ inputs.mongodb-password }}
    - ${{ inputs.host-container-hostname }}
